version: "3.9"

services:
   postgres: 
     image: postgres:17
     container_name: cfd_postgres
     environment: 
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: cfd_db
     ports:
       - 5432:5432
     volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: