version: "3.9"

services:
   postgres: 
     image: timescale/timescaledb:2.22.0-pg17
     container_name: cfd_timescaledb
     environment: 
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: cfd_db
     ports:
       - 5432:5432
     volumes:
       - pgdata:/var/lib/postgresql/data
   
   redis:
     image: redis:latest
     container_name: cfd-redis-instance
     restart: always
     ports:
       - "6379:6379"
     volumes:
       - redis_data:/var/lib/redis/data
volumes:
  pgdata:
  redis_data:
  